### ISSUE TITLE
springcloud oauth2 集群配置

### ISSUE THREAD

**Issue by elfasd** [babylikebird/Micro-Service-Skeleton#14]
您好，如果我有多个autherver ，那么客户端应该怎么配置呢？难道cloud内部也要架个nginx么。。。

**Comment by babylikebird** [comment]
> 您好，如果我有多个autherver ，那么客户端应该怎么配置呢？难道cloud内部也要架个nginx么。。。

目前只能这样。另外一种方式可以直接把认证授权中心放在gateway上。
