### ISSUE TITLE
请教一下，升级后oather一直报401

### ISSUE THREAD

**Issue by zengjuemin** [babylikebird/Micro-Service-Skeleton#20]
我新下了代码后，在用postman进行http://localhost:9030/uaa/oauth/token时status=401,有人能说一下吗

**Comment by zengjuemin** [comment]
关于上述问题，在fank 帮助下，已经解决了，主要原因就是这一次升级后数据库脚本发生很大变化，原来rc_开头的表，全部换成sys_开头了，另外，原来oauth_client_details 表 webApp那条记录密码由原来的webApp换成123456再加密的！在此感谢fank,同时在这里也提出下一个问题就是monitor那个工程现在是不是不能用了，一是pom.xml注了zipkin的全部，二是MonitorApplication的注解@EnableZipkinServer出错！
望各位同仁或已解决了朋友，提出指教一下！

**Comment by AkiraRex** [comment]
我也遇到了同样的问题，http://localhost:9030/uaa/oauth/token时status=401
但是直接访问授权中心http://localhost:9060/oauth/token时，是可以正确返回token的，
请问是什么问题呢

**Comment by babylikebird** [comment]
> 我也遇到了同样的问题，[http://localhost:9030/uaa/oauth/token时status=401](http://localhost:9030/uaa/oauth/token%E6%97%B6status=401)
> 但是直接访问授权中心[http://localhost:9060/oauth/token时，是可以正确返回token的，](http://localhost:9060/oauth/token%E6%97%B6%EF%BC%8C%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%AD%A3%E7%A1%AE%E8%BF%94%E5%9B%9Etoken%E7%9A%84%EF%BC%8C)
> 请问是什么问题呢
我把代码注释掉了。
zuul会过滤点敏感的Header，不会下发到后面的服务，需要打开
zuul:
  routes:
    uaa:
      sensitiveHeaders:

**Comment by babylikebird** [comment]
@AkiraRex 
zuul会过滤点敏感的Header，不会下发到后面的服务，需要打开
zuul:
  routes:
    uaa:
      sensitiveHeaders:

**Comment by AkiraRex** [comment]
非常感谢，我已经发现是这个问题了。谢谢
