### ISSUE TITLE
各个模块服务都启动起来了，但是用postman获取token，返回空

### ISSUE THREAD

**Issue by square-box** [babylikebird/Micro-Service-Skeleton#26]
![image](https://user-images.githubusercontent.com/46339224/53295927-afccae80-3840-11e9-827f-b723e3df4783.png)
![image](https://user-images.githubusercontent.com/46339224/53295930-b65b2600-3840-11e9-98a3-69cc4e1a96cc.png)
![image](https://user-images.githubusercontent.com/46339224/53295931-bb1fda00-3840-11e9-869d-9b922a02c23d.png)
请问我写的有什么问题么？后台启动也没有报错。大佬看到了麻烦指点一下，搞了好几天了。。

**Comment by ligai322** [comment]
请问你解决了吗

**Comment by nunuqq1** [comment]
同样的问题
