### ISSUE TITLE
gateway  怎么拿到用户拥有的url的

### ISSUE THREAD

**Issue by zwylovejava** [babylikebird/Micro-Service-Skeleton#9]
认证服务器存的也只是  存的rolecode
        Result<List<RoleVo>> roleResult = roleService.getRoleByUserId(userVo.getId());
        if (roleResult.getCode() != 100){
            List<RoleVo> roleVoList = roleResult.getData();
            for (RoleVo role:roleVoList){
                //角色必须是ROLE_开头，可以在数据库中设置
                GrantedAuthority grantedAuthority = new SimpleGrantedAuthority("ROLE_"+role.getValue());
                grantedAuthorities.add(grantedAuthority);
                //获取权限
                Result<List<MenuVo>> perResult  = permissionService.getRolePermission(role.getId());
                if (perResult.getCode() != 100){
                    List<MenuVo> permissionList = perResult.getData();
                    for (MenuVo menu:permissionList
                            ) {
                        GrantedAuthority authority = new SimpleGrantedAuthority(menu.getCode());
                        grantedAuthorities.add(authority);
                    }
                }
而gateway
  if (antPathMatcher.match(authority.getAuthority(),requestUrl))

**Comment by babylikebird** [comment]
@zwylovejava 
security:
  oauth2:
    resource:
      user-info-uri:  http://localhost:9060/user
      prefer-token-info: false
